build:	
	gcc open_file_specifed_mode.c -o open_file_specifed_mode

clean:
	rm -rf open_file_specifed_mode

run:
	./open_file_specifed_mode ${ARGS}

help:

	@echo "./open_file_specifed_mode filename mode"
	@echo "modes- 1.O_RDONLY 2.O_WRONLY 3.O_RDWR 4.O_CREAT 5.O_TRUNC 6.APPEND"
